apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: demo-slack-event-listener
spec:
  namespaceSelector: {}
  resources: {}
  serviceAccountName: pipeline
  triggers:
    - bindings:
        - kind: TriggerBinding
          ref: demo-trigger-binding
      name: slack-trigger
      template:
        ref: demo-trigger-template
