kind: DevWorkspace
apiVersion: workspace.devfile.io/v1alpha2
metadata:
  name: nodejs-workspace
spec:
  contributions:
    - kubernetes:
        name: che-code-nodejs-mongodb
      name: che-code-nodejs-mongodb
  routingClass: che
  started: true
  template:
    projects:
      - name: my-project
        git:
          remotes:
            origin: https://github.com/devspaces-samples/nodejs-mongodb-sample
    components:
      - name: tooling-container
        container:
          image: quay.io/devfile/universal-developer-image:ubi8-latest
